### ISSUE TITLE
Prevent using floatval function

### ISSUE THREAD

**Issue by froemken** [mittwald/typo3-mw-cache-widget#3]
Hello Mittwald-Team,

could you please switch to `(float)` instead of using `floatval()`?

Stefan

**Comment by martin-helmich** [comment]
Hey @froemken, thanks for the report. We generally don't require (nor want to encourage) issues for single CGL violations. Eventually, we're going to switch to just testing for PSR-12 compliance in the CI pipeline, anyway (see #7); up until then, any PRs for quick CGL fixes are welcome.
